# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Args: {confirm: boolean}
$data modify storage aj:temp confirm set value $(confirm)
execute unless data storage aj:temp {confirm: 1} run tellraw @a "Are you sure you want to remove all Animated Java rigs from the world? Run this command again with {confirm: true} to confirm."
execute if data storage aj:temp {confirm: 1} run function animated_java:global/remove/zzz/2