# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.armor_stand_merge.animation.walk.playing] run \
	function animated_java:armor_stand_merge/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_merge.animation.jumping_jacks.playing] run \
	function animated_java:armor_stand_merge/animations/jumping_jacks/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_merge.animation.think.playing] run \
	function animated_java:armor_stand_merge/animations/think/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_merge.animation.enter_sit.playing] run \
	function animated_java:armor_stand_merge/animations/enter_sit/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_merge.animation.sitting.playing] run \
	function animated_java:armor_stand_merge/animations/sitting/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_merge.animation.exit_sitting.playing] run \
	function animated_java:armor_stand_merge/animations/exit_sitting/zzz/on_tick