/// <reference types="node"/>
// ---------------------------------------------------------------------
// This template script adds a few useful arguments to the mcbuild cli:
// -clean: Errases the data folder before building.
// ---------------------------------------------------------------------
const fs = require('fs')
const x = {
	preBuild: build => {
		if (process.argv.includes('-clean')) {
			try {
				fs.rmSync('./data/', { recursive: true })
			} catch (e) {}
			fs.mkdirSync('./data/')
		}
	},
	postBuild: build => {},
}
module.exports = {
	libDir: null, // default: "null", determine where mcb looks for libraries, default is the bundled install location
	generatedDirName: 'zzz', // default: "zzz", the name of the directory where mcb will put generated files
	internalScoreboardName: 'i', // default: "mcb.internal", the name of the internal scoreboard
	header: '# Developed by SnaveSutit (Discord: SnaveSutit#0042 | Email: SnaveSutit@gmail.com)\n# built using mc-build (https://github.com/mc-build/mc-build)', // default: "#This file was generated by mcb\n", the header to put at the top of supported generated files
	ioThreadCount: 1, // default: 1, the number of threads to use for IO operations, 1 is syncronous.
	setup: null, // default: null, a function that will be called to allow binding to mcb events.
}
