# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
#ARGS: {frame: int}
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.head] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].head
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.left_arm] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].left_arm
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.right_arm] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].right_arm
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.body] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].body
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.right_leg2] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].right_leg2
$execute on passengers run data modify entity @s[tag=aj.armor_stand_modify.bone.left_leg] {} merge from storage aj.armor_stand_modify:animations list.walk.frames[$(frame)].left_leg