# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# This command will be added for each animation.
execute if entity @s[tag=aj.armor_stand_modify.animation.walk.playing] run \
	function animated_java:armor_stand_modify/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_modify.animation.jumping_jacks.playing] run \
	function animated_java:armor_stand_modify/animations/jumping_jacks/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_modify.animation.think.playing] run \
	function animated_java:armor_stand_modify/animations/think/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_modify.animation.enter_sit.playing] run \
	function animated_java:armor_stand_modify/animations/enter_sit/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_modify.animation.sitting.playing] run \
	function animated_java:armor_stand_modify/animations/sitting/zzz/on_tick
execute if entity @s[tag=aj.armor_stand_modify.animation.exit_sitting.playing] run \
	function animated_java:armor_stand_modify/animations/exit_sitting/zzz/on_tick